name: Run unit tests
description: "Run lint, build and tests"

runs:
  using: "composite"
  steps:
    - name: Run backend linting
      shell: bash
      run: npm run lint

    - name: Build backend
      shell: bash
      run: npm run build

    - name: Run backend unit tests
      shell: bash
      run: npm test
