name: Release OIBus upgrade tool version


on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  tests:
    name: 'Test OIBus'
    uses: ./.github/workflows/tests.yml

  release-please:
    needs: tests
    name: 'Tag new version'
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{ steps.release.outputs.tag_name }}
      release-created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          signoff: "Optimistik SAS <optimistiksas@users.noreply.github.com>"

  build-binaries:
    needs: release-please
    name: Build for ${{ matrix.config['friendlyName'] }}
    runs-on: ${{ matrix.config['os'] }}
    strategy:
      matrix:
        config:
          - { friendlyName: 'Mac OS x64', os: 'macos-latest',   platform: 'macos', archiveName: 'oibus-macos.zip', zip: 'zip -r' }
          - { friendlyName: 'Windows x64', os: 'windows-latest', platform: 'win',   archiveName: 'oibus-win32x64.zip', zip: '7z a -tzip' }
          - { friendlyName: 'Linux x64', os: 'ubuntu-latest',  platform: 'linux', archiveName: 'oibus-linux.tar.gz', zip: 'tar -czvf' }
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - name: Setup environment
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/setup_environment
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}

      - name: Build OIBus for ${{ matrix.config['friendlyName'] }}
        if: ${{ steps.release.outputs.release_created }}
        run: npm run build:${{ matrix.config['platform'] }}

      - name: Test OIBus run for ${{ matrix.config['friendlyName'] }}
        if: ${{ steps.release.outputs.release_created }}
        run: |
          cd ./build/bin/${{ matrix.config['platform'] }}
          ./oibus --config ../../../data-folder --check true

      - name: Package OIBus for ${{ matrix.config['friendlyName'] }}
        if: ${{ steps.release.outputs.release_created }}
        run: |
          cd build/bin/${{ matrix.config['platform'] }}
          ${{ matrix.config['zip'] }} ../${{ matrix.config['archiveName'] }} .

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload ${{ needs.release-please.outputs.tag_name }} ./build/bin/${{ matrix.config['archiveName'] }}
